### PR TITLE
8301400: Allow additional characters for GB18030-2022 support

### PR DESCRIPTION
**Pull request by naotoj**
Please review the changes to the Reference Implementation of the proposed Maintenance Release of the Java SE 8 (https://mail.openjdk.org/pipermail/jdk8u-dev/2023-February/016710.html). The RI contains a portion of previously released Maintenance Release 2 of the Java SE 8 (Unicode Characters) updates as well. (https://jcp.org/aboutJava/communityprocess/maintenance/jsr337/jsr337-mr2-changes.html#s3)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8301557](https://bugs.openjdk.org/browse/JDK-8301557) to be approved

### Issues
 * [JDK-8301400](https://bugs.openjdk.org/browse/JDK-8301400): Allow additional characters for GB18030-2022 support
 * [JDK-8301557](https://bugs.openjdk.org/browse/JDK-8301557): Allow additional characters for GB18030-2022 support (**CSR**)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - Author)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Contributors
 * Justin Lu `<jlu@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-ri pull/10/head:pull/10` \
`$ git checkout pull/10`

Update a local copy of the PR: \
`$ git checkout pull/10` \
`$ git pull https://git.openjdk.org/jdk8u-ri pull/10/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10`

View PR using the GUI difftool: \
`$ git pr show -t 10`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-ri/pull/10.diff">https://git.openjdk.org/jdk8u-ri/pull/10.diff</a>

</details>

### CODE REVIEW

**Review by gnu-andrew — APPROVED** [review]
Changes look correct to me, assuming the new test passes.

Most of these changes are drawn from JDK-8211398 (the currency and Japanese era addition, and the new test) which made it to 8u211/212, but not a new reference implementation. I expect the changes for 8u382 will be simpler as they can just build on top of 8211398, as the separate commits here suggest.

**Comment by naotoj** [comment]
> Most of these changes are drawn from JDK-8211398 (the currency and Japanese era addition, and the new test) which made it to 8u211/212, but not a new reference implementation. I expect the changes for 8u382 will be simpler as they can just build on top of 8211398, as the separate commits here suggest.

Thanks, Andrew. Yes, it will be much simpler for the existing 8u line.

**Review by LanceAndersen — APPROVED** [review]

**Review by irisclark — APPROVED** [review]

**Comment by gnu-andrew** [comment]
Approved with `jdk8u43-fix-yes`

**Review by AlanBateman — APPROVED** [review]

**Pull request closed without merging**
