### PR TITLE
8307779: Relax the java.awt.Robot specification

### PR DESCRIPTION
**Pull request by azvegint**
Please review the doc only backport PR of https://github.com/openjdk/jdk/pull/13809.

It is backport of the original commit + build failure fix. 

8u  does not have the changes related to the to the missing `createMultiResolutionScreenCapture` method.

CSR: [JDK-8331038](https://bugs.openjdk.org/browse/JDK-8331038)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8331038](https://bugs.openjdk.org/browse/JDK-8331038) to be approved
- [x] [JDK-8307779](https://bugs.openjdk.org/browse/JDK-8307779) needs maintainer approval

### Issues
 * [JDK-8307779](https://bugs.openjdk.org/browse/JDK-8307779): Relax the java.awt.Robot specification (**Bug** - P3 - Approved)
 * [JDK-8331038](https://bugs.openjdk.org/browse/JDK-8331038): Relax the java.awt.Robot specification (**CSR**)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - Author)
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-ri.git pull/15/head:pull/15` \
`$ git checkout pull/15`

Update a local copy of the PR: \
`$ git checkout pull/15` \
`$ git pull https://git.openjdk.org/jdk8u-ri.git pull/15/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15`

View PR using the GUI difftool: \
`$ git pr show -t 15`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-ri/pull/15.diff">https://git.openjdk.org/jdk8u-ri/pull/15.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-ri/pull/15#issuecomment-2075567931)

### CODE REVIEW

**Review by prrace — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Spec and implementation changes as expected for 8u44.

Associated CSR (JDK-8331038 already Approved.

**Review by LanceAndersen — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
Change looks good, adapting for older copyright and context, and the lack of `createMultiResolutionScreenCapture`
Again, as with 17u, not sure if we should mention JDK-8308370 or not. We usually would for a regular 8u backport.

**Comment by gnu-andrew** [comment]
> Change looks good, adapting for older copyright and context, and the lack of `createMultiResolutionScreenCapture` Again, as with 17u, not sure if we should mention JDK-8308370 or not. We usually would for a regular 8u backport.

8u also adds `checkScreenCaptureAllowed` as 11u does. I missed this earlier due to the documentation differences between 17 & 8.

**Pull request closed without merging**
